### ISSUE TITLE
Feature Request: Add a region flag to biscuit get/export

### ISSUE THREAD

**Issue by bobziuchkovski** [dcoker/biscuit#10]
When using multiple KMS regions, biscuit currently [attempts to decrypt all values with the given name across all regions, accepting the first value that decrypts successfully](https://github.com/dcoker/biscuit/blob/master/commands/get.go#L41-L54).  This introduces a **ton** of network round trip latency when the system performing the decryption is on the other side of the world from the KMS region it is attempting to access.

It would be terrific if the `biscuit get` and `biscuit export` commands accepted a flag to limit the KMS region(s) they attempt to access.  This would ensure geographic locality and reduce network latency.

In our tests, `biscuit export` takes approximately 10 seconds to execute for our app config when biscuit accesses a remote KMS region, as opposed to 0.8 seconds when accessing a local KMS region (matching the server location).

If you're open to a PR, I'd be happy to submit one.

**Comment by dcoker** [comment]
Hi Bob!

Yes, I'd be happy to review a PR for this. The current implementation is simple because I hadn't figured out an elegant and simple way to order the regions by estimated latency. I think a command line flag is a good compromise. Perhaps the flag could use the value of `AWS_REGION` or `AWS_DEFAULT_REGION` as a default.

Thank you.

**Comment by dcoker** [comment]
I've just pushed a new feature that might address this issue. `get` and `export` now support a flag for prioritizing one or more regions such that keys in those regions are tried before keys from other regions. 

```
  get --filename=FILE [<flags>] <name>
    Read a secret.

    -p, --aws-region-priority=REGIONS  
                         Comma-delimited list of AWS regions to prefer for
                         decryption operations. Biscuit will attempt to use the
                         KMS endpoints in these regions before trying the other
                         regions. If the environment variable AWS_REGION is set,
                         it will be used as the default value.
    -o, --output=FILE    Write to FILE instead of stdout.
    -f, --filename=FILE  Name of file storing the secrets. If the environment
                         variable BISCUIT_FILENAME is set, it will be used as
                         the default value.
```

See 40d68657a09e332dc4e55da5ccfc62ed4accd6fe for more info.

Thanks for raising this issue!
