### ISSUE TITLE
Support Multiple Session Profiles

### ISSUE THREAD

**Issue by GICodeWarrior** [dcoker/biscuit#11]
Right now, it's difficult to use biscuit in an environment with multiple AWS accounts since it only uses the credentials in the default profile.

Adding an option to specify the profile would be helpful.

https://docs.aws.amazon.com/sdk-for-go/api/aws/session/#hdr-Create_Session_With_Option_Overrides

**Comment by dcoker** [comment]
biscuit delegates profile selection to the AWS golang SDK. You can specify a different profile by setting the `AWS_PROFILE` environment variable. Example (in bash):

```
$ AWS_PROFILE=client biscuit kms get-caller-identity
```

If there is a specific feature which breaks with this option, please feel free to re-open this issue.

Thanks for the report!
