### ISSUE TITLE
Support selection of credentials from ~/.aws/credentials ini file

### ISSUE THREAD

**Issue by qwwqwwq** [dcoker/biscuit#2]
Could biscuit benefit from a `--profile` flag that selects which credentials entry in the ini file to use? Or is there a better way to manage using with multiple accounts?

**Comment by dcoker** [comment]
Thanks for the suggestion, Jeff! Yes, biscuit should allow you to specify a profile. I'll accept a patch for that.

You might consider using https://github.com/dcoker/awsmfa to manage multiple accounts. With the `-c skip` flag, it can be a useful way to update the `default` profile from your `~/.aws/credentials` file (no MFA required). Example:

```
awsmfa -i work -c skip      # writes session credentials for [work] to [default]
awsmfa -i hackathon -c skip # writes session credentials for [hackathon] to [default]
```

**Comment by gregwebs** [comment]
Setting the `AWS_PROFILE` environment variable works.

**Comment by dcoker** [comment]
Thanks!
