### ISSUE TITLE
doesn't accept credential with a leading minus

### ISSUE THREAD

**Issue by gregwebs** [dcoker/biscuit#3]
A leading minus gets interpreted by biscuit as a CLI arg. However, many credentials contain randomly generated characters and thus can begin with a minus.

This can be worked around by converting the argument to a file: `--from-file` <(echo -n "$secret")`.

I don't know the CLI parser well enough to suggest an improvement that works well with it. But in general one possibility is using `--` to indicate an end to any flags.

At least having this issue as documentation may be helpful.

**Comment by dcoker** [comment]
Hey @gregwebs!

Good find! I have investigated and it looks like the flag parser ([kingpin](https://github.com/alecthomas/kingpin)) does allow `--` as an arg separator. Example:

```
$ biscuit put -f secrets.yml password -- --leading-dashes--
$ biscuit get -f secrets.yml password
--leading-dashes--
```

I agree this should be in the docs. I'll add it in the next revision, or I'd be happy to review a PR from you!

Thanks!
