### ISSUE TITLE
Faster exporting+decryption of entire file?

### ISSUE THREAD

**Issue by suan** [dcoker/biscuit#7]
I've noticed that doing `biscuit export` is very slow as it seems to be decrypting one key at a time. Is there a way to decrypt them all at once, or one that is faster?

**Comment by dcoker** [comment]
Hi suan -

Yeah, it is slow! Each secret is encrypted with a unique key, and biscuit has to unwrap each key by making an API call to KMS. Using a worker-pool model for decrypting multiple secrets in parallel would probably be an easy change. I would be happy to review a PR for this.

Thanks!
