### ISSUE TITLE
InvalidSignatureException: Signature expired 19700101T000014Z is now earlier than ...

### ISSUE THREAD

**Issue by bobziuchkovski** [dcoker/biscuit#8]
Running the latest biscuit release on Mac OS Sierra yields sporadic `InvalidSignatureException` errors.  Each of them reference `19700101T000014Z is now earlier than <<<current time>>>`.  It looks like a zero value timestamp is being serialized and sent over the wire by the aws sdk.

Full error:

```
Error: unable to decrypt, skipping: InvalidSignatureException: Signature expired: 19700101T000014Z is now earlier than 20161108T220908Z (20161108T221408Z - 5 min.)
	status code: 400, request id: ab80e27a-a600-11e6-8421-b152a8895f46
```

When I compile biscuit myself against Go 1.7.3 with a fresh checkout, **I cannot reproduce the error**.  Hence, I think either one of the biscuit upstream dependencies has been patched since the latest biscuit release (such as the go sdk), or perhaps the release is compiled with an older version of Go that is lacking some relevant fix.

In any event, would you be willing to release a new build compiled against Go 1.7.3 and against updated upstream dependencies?  I'd be happy to test and report whether or not I encounter the `InvalidSignatureException`.

Or, if you'd prefer, I'd be happy to submit a PR that enhances your Travis integration to build and publish releases directly to GitHub from Travis.  I use something similar for my DeVo project: https://github.com/bobziuchkovski/devo/blob/master/scripts/travis_deploy.sh is called from https://github.com/bobziuchkovski/devo/blob/master/.travis.yml .

**Comment by dcoker** [comment]
Hi!

Thanks for the detailed report and the offer to improve the Travis configs!

I've just pushed b4bb2c4 which bumps golang to 1.7 and builds against the latest AWS SDK. This is released as [v0.1.3](https://github.com/dcoker/biscuit/releases/tag/v0.1.3).

The existing [.travis.yml](https://github.com/dcoker/biscuit/blob/master/.travis.yml#L23) uses the built-in Travis support for creating github releases, and the [Makefile](https://github.com/dcoker/biscuit/blob/master/Makefile#L63) has some Docker and [gox]( https://github.com/mitchellh/gox) voodoo to do the cross-compiling.

I'll close this issue now, but feel free to re-open if the `InvalidSignatureException` errors are still appearing for you.

Thanks!
